# Site settings
title: The art of confusion
header-img: img/home-bg.png
email: gonzalezdennis6@gmail.com
copyright_name: independnt
description: > # this means to ignore newlines until "baseurl:"
  and making sense of it
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  independnt
learn_profile: independnt
email_username: gonzalezdennis6@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
